# Generated by Django 5.2.8 on 2025-11-30 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('sports_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sports',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_num', models.CharField(max_length=8)),
                ('reservation_date', models.DateTimeField()),
                ('hour', models.JSONField()),
                ('facility', models.CharField(max_length=100)),
                ('delete_yn', models.IntegerField(default=0)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member.member')),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facilityinfo')),
                ('reservation_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.reservation')),
            ],
            options={
                'db_table': 'time_slot',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='t_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.timeslot'),
        ),
    ]
