# Generated by Django 5.2.8 on 2025-12-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_timeslot_delete_yn'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
