# Generated by Django 5.2.8 on 2025-12-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_remove_reservation_expire_date_reservation_expire_yn'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment',
            field=models.IntegerField(default=0),
        ),
    ]
