# Generated by Django 5.2.8 on 2025-11-30 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('board_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'catergory',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('view_cnt', models.IntegerField(default=0)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('always_on', models.IntegerField(default=1)),
                ('etc_int1', models.IntegerField(blank=True, null=True)),
                ('etc_int2', models.IntegerField(blank=True, null=True)),
                ('etc_int3', models.IntegerField(blank=True, null=True)),
                ('etc_text1', models.CharField(blank=True, max_length=100, null=True)),
                ('etc_text2', models.CharField(blank=True, max_length=100, null=True)),
                ('etc_text3', models.CharField(blank=True, max_length=100, null=True)),
                ('etc_date1', models.DateTimeField(blank=True, null=True)),
                ('etc_date2', models.DateTimeField(blank=True, null=True)),
                ('etc_date3', models.DateTimeField(blank=True, null=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member.member')),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.category')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
