# Generated by Django 5.2.8 on 2025-11-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('birthday', models.CharField(max_length=20)),
                ('gender', models.IntegerField()),
                ('addr1', models.CharField(max_length=200)),
                ('addr2', models.CharField(blank=True, max_length=200, null=True)),
                ('addr3', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_num', models.CharField(max_length=500, unique=True)),
                ('delete_yn', models.IntegerField(default=0)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
