# Generated by Django 5.2.8 on 2025-12-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_manager_yn'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='delete_reason',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
