# Generated by Django 5.2.8 on 2025-12-16 11:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0003_member_delete_reason'),
        ('reservation', '0006_reservation_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_key', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('MOCK', 'Mock'), ('TOSS', 'Toss'), ('KAKAO', 'Kakao')], default='MOCK', max_length=20)),
                ('method', models.CharField(choices=[('MOCK', 'Mock'), ('CARD', 'Card'), ('TRANSFER', 'Transfer')], default='MOCK', max_length=20)),
                ('status', models.IntegerField(choices=[(0, 'READY'), (1, 'DONE'), (2, 'FAILED'), (3, 'CANCELED')], default=0)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('fail_reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('method_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method_type', models.CharField(default='MOCK_CARD', max_length=30)),
                ('display_name', models.CharField(default='모의 카드', max_length=50)),
                ('masked_value', models.CharField(default='****-****-****-1234', max_length=30)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to='payment.payment')),
            ],
            options={
                'db_table': 'payment_method',
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_no', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('amount', models.IntegerField(default=0)),
                ('currency', models.CharField(default='KRW', max_length=10)),
                ('status', models.IntegerField(choices=[(0, 'CREATED'), (1, 'PAID'), (2, 'CANCELED'), (3, 'FAILED'), (4, 'EXPIRED')], default=0)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_orders', to='member.member')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='reservation.reservation')),
            ],
            options={
                'db_table': 'payment_order',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.paymentorder'),
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payment.payment')),
            ],
            options={
                'db_table': 'payment_log',
                'indexes': [models.Index(fields=['event_type', 'reg_date'], name='payment_log_event_t_8437c3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['order_no'], name='payment_ord_order_n_403466_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status', 'reg_date'], name='payment_ord_status_32d192_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_key'], name='payment_payment_8529f7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'requested_at'], name='payment_status_0a652e_idx'),
        ),
    ]
