# Generated by Django 5.2.8 on 2025-11-30 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('community_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('contents', models.TextField()),
                ('region', models.CharField(max_length=10)),
                ('sport_type', models.CharField(max_length=10)),
                ('facility', models.CharField(default='미정', max_length=100)),
                ('num_member', models.IntegerField()),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('chat_url', models.CharField(blank=True, max_length=100, null=True)),
                ('view_cnt', models.IntegerField(default=0)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('reservation_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.reservation')),
            ],
            options={
                'db_table': 'community',
            },
        ),
        migrations.CreateModel(
            name='EndStatus',
            fields=[
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recruitment.community')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_set_date', models.DateField()),
                ('end_stat', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'end_status',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility', models.CharField(max_length=100)),
                ('rated', models.IntegerField(default=0)),
                ('comments', models.TextField()),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recruitment.community')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member.member')),
            ],
            options={
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='JoinStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_status', models.IntegerField(default=0)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.community')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'join_stat',
                'constraints': [models.UniqueConstraint(fields=('member_id', 'community_id'), name='pk_join_stat')],
            },
        ),
    ]
