# Generated by Django 5.2.8 on 2025-12-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='region2',
            field=models.CharField(default='강남구', max_length=10),
            preserve_default=False,
        ),
    ]
