# Generated by Django 5.2.8 on 2025-12-12 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_community_region2'),
        ('reservation', '0006_reservation_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='reservation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='community_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recruitment.community'),
        ),
    ]
