# Generated by Django 5.2.8 on 2025-11-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImg',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('context', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hero_img',
            },
        ),
    ]
