# Generated by Django 5.2.8 on 2025-12-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimg',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heroimg',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
