# Generated by Django 5.2.8 on 2025-12-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_heroimg_end_date_alter_heroimg_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimg',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
