# Generated by Django 5.2.8 on 2025-12-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_heroimg_delete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimg',
            name='img_status',
            field=models.IntegerField(default=0),
        ),
    ]
