# Generated by Django 5.2.8 on 2025-11-30 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='AddInfo',
            fields=[
                ('add_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=20)),
                ('file_name', models.CharField(max_length=100)),
                ('encoded_name', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('article_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.article')),
            ],
            options={
                'db_table': 'add_info',
            },
        ),
    ]
