# Generated by Django 5.2.8 on 2025-11-30 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0001_initial'),
        ('common', '0001_initial'),
        ('facility', '0002_initial'),
        ('manager', '0001_initial'),
        ('member', '0001_initial'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addinfo',
            name='community_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.community'),
        ),
        migrations.AddField(
            model_name='addinfo',
            name='facility_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.facilityinfo'),
        ),
        migrations.AddField(
            model_name='addinfo',
            name='img_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.heroimg'),
        ),
        migrations.AddField(
            model_name='comment',
            name='article_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.article'),
        ),
        migrations.AddField(
            model_name='comment',
            name='board_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.board'),
        ),
        migrations.AddField(
            model_name='comment',
            name='community_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recruitment.community'),
        ),
        migrations.AddField(
            model_name='comment',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member.member'),
        ),
    ]
