# Generated by Django 5.2.8 on 2025-12-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addinfo',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
