# Generated by Django 5.2.8 on 2025-12-03 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_addinfo_path'),
        ('facility', '0006_facilityinfo_view_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='facility',
            field=models.ForeignKey(blank=True, db_column='facility', null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.facility', to_field='faci_cd'),
        ),
    ]
