# Generated by Django 5.2.8 on 2025-12-09 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_initial_data'),
        ('common', '0004_comment_facility'),
        ('facility', '0007_facility_view_cnt_facilityinfo_rs_posible'),
        ('recruitment', '0002_community_region2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='board_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.board'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='community_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.community'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='facility',
            field=models.ForeignKey(blank=True, db_column='facility', null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.facility', to_field='faci_cd'),
        ),
    ]
