# Generated by Django 5.2.8 on 2025-11-30 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faci_cd', models.CharField(max_length=50, unique=True)),
                ('faci_nm', models.CharField(blank=True, max_length=200, null=True)),
                ('faci2_nm', models.CharField(blank=True, max_length=200, null=True)),
                ('cp_nm', models.CharField(blank=True, max_length=50, null=True)),
                ('cpb_nm', models.CharField(blank=True, max_length=50, null=True)),
                ('fcob_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('ftype_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('faci_addr', models.CharField(blank=True, max_length=300, null=True)),
                ('faci_road_addr', models.CharField(blank=True, max_length=300, null=True)),
                ('faci_daddr', models.CharField(blank=True, max_length=300, null=True)),
                ('faci_road_daddr', models.CharField(blank=True, max_length=300, null=True)),
                ('faci_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('faci_lat', models.FloatField(blank=True, null=True)),
                ('faci_lot', models.FloatField(blank=True, null=True)),
                ('faci_stat_nm', models.CharField(blank=True, max_length=50, null=True)),
                ('schk_tot_grd_nm', models.CharField(blank=True, max_length=50, null=True)),
                ('schk_tot_grd_cd', models.CharField(blank=True, max_length=5, null=True)),
                ('faci_mng_type_cd', models.CharField(blank=True, max_length=20, null=True)),
                ('inout_gbn_nm', models.CharField(blank=True, max_length=10, null=True)),
                ('atnm_chk_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('faci_tel_no', models.CharField(blank=True, max_length=50, null=True)),
                ('faci_homepage', models.CharField(blank=True, max_length=200, null=True)),
                ('faci_gfa', models.CharField(blank=True, max_length=50, null=True)),
                ('base_ymd', models.CharField(blank=True, max_length=20, null=True)),
                ('reg_dt', models.CharField(blank=True, max_length=20, null=True)),
                ('faci_reg_ymd', models.CharField(blank=True, max_length=20, null=True)),
                ('faci_upd_ymd', models.CharField(blank=True, max_length=20, null=True)),
                ('schk_visit_ymd', models.CharField(blank=True, max_length=20, null=True)),
                ('schk_open_ymd', models.CharField(blank=True, max_length=20, null=True)),
                ('sdwn_ymd', models.CharField(blank=True, max_length=20, null=True)),
                ('th_ymd', models.CharField(blank=True, max_length=20, null=True)),
                ('row_num', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'facility',
            },
        ),
        migrations.CreateModel(
            name='FacilityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='facility_photos/')),
                ('reservation_time', models.JSONField(blank=True, null=True)),
                ('faci_nm', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('homepage', models.CharField(blank=True, max_length=200, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.facility')),
            ],
            options={
                'db_table': 'facility_info',
            },
        ),
    ]
