# Generated by Django 5.2.8 on 2025-11-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityinfo',
            name='sports',
            field=models.ManyToManyField(to='reservation.sports'),
        ),
    ]
