# Generated by Django 5.2.8 on 2025-11-30 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_initial'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityinfo',
            name='sports',
        ),
        migrations.AddField(
            model_name='facilityinfo',
            name='sports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.sports'),
        ),
    ]
