# Generated by Django 5.2.8 on 2025-11-30 05:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_alter_facility_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
