# Generated by Django 5.2.8 on 2025-12-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0005_remove_facilityinfo_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityinfo',
            name='view_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
