# Generated by Django 5.2.8 on 2025-12-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0008_facility_faci_gb_nm_facilityinfo_faci_gb_nm'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityinfo',
            name='faci_stat_nm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
